#pragma once

enum BLINKER_LIGHTS_MODE{
    LEFT_DIRECTION_INDICATOR,
    RIGHT_DIRECTION_INDICATOR,
    EMERGENCY_LIGHTS,
    BLINKERS_OFF
};

enum REAR_LIGHTS_MODE{
    REAR_LIGHTS_ON,
    BREAK_LIGHTS_ON,
    BREAK_LIGHTS_OFF,
    REAR_LIGHTS_OFF,
    LIGHTS_OFF
};

enum FRONT_LIGHTS_MODE{
    LOWBEAM_LIGHTS_ON,
    HIGHBEAM_LIGHTS_ON,
    FRONT_LIGHTS_OFF
};